package database

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

type Product struct {
	Name      string `json:"name" binding:"min=2,max=20"`
	Count     int    `json:"count" binding:"min=1,max=100"`
	Check_box bool   `json:"check_box"`
}

func DatabaseConnection() *sql.DB {

	connStr := "user=postgres password=root dbname=godb sslmode=disable"
	DB, err := sql.Open("postgres", connStr)
	if err != nil {
		panic(err)
	}

	_, err = DB.Exec(`CREATE TABLE IF NOT EXISTS Products  (
    	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    	name  varchar(30) NOT NULL,
    	count integer NOT NULL,
    	check_box boolean NOT NULL
	)`)
	if err != nil {
		panic(err)
	}

	fmt.Println("Database connection successful...")
	return DB
}
